### ISSUE TITLE
Issue when using this module on Call Recorder on Android 10 & 11

### ISSUE THREAD

**Issue by Marvinoo** [BlueCat300/XposedAppSettings#10]
I'm using this call recorder : https://play.google.com/store/apps/details?id=org.skvalex.cr
When I hook that app to modify the DPI value by App Settings Reborn, the CR fails to record all of the call (something kills the CR recording process in the background when I use ur module on it) and all of the calls recordings clips come out incomplete. 
Steps to reproduce : By trying to record a call with CR hooked by this module and once again unhooked.

**Comment by BlueCat300** [comment]
I checked this application, no crashes was found when recording a call with enabled DPI.
The problems you described are more like protection triggers after rebuilding or re-signing the application. Most likely, the installed apk is pirated and badly cracked. I have already dealt with this application regarding its reassembly and the symptoms were just same.
Maybe you should try to install the original from google play and check again?
