### ISSUE TITLE
Auto rotate always landscape bug on mame4droid emulator on android

### ISSUE THREAD

**Issue by Gamemulatorer** [BlueCat300/XposedAppSettings#4]
The always landscape or auto rotate on app settings reborn has bug on mame4droid emulator.
![Screenshot_20200909-095806](https://user-images.githubusercontent.com/37603562/92545876-b33d5480-f283-11ea-9248-1e197bd0b3e6.png)
![Screenshot_20200909-095903](https://user-images.githubusercontent.com/37603562/92545890-be908000-f283-11ea-9d2a-bcf250c64da4.png)

### Correct Landscape (Device Auto Rotation)
![Screenshot_20200909-100425](https://user-images.githubusercontent.com/37603562/92545940-e1bb2f80-f283-11ea-879f-0760c73d2f71.png)

**Comment by Gamemulatorer** [comment]
### Phone Specs
Android 6.0.1
Mali-450 GPU
2GB RAM

### Xposed Installer 3.1.5 by dvdandroid
![Screenshot_20200909-100829](https://user-images.githubusercontent.com/37603562/92546132-71f97480-f284-11ea-9535-43a2ba672fab.png)

**Comment by Gamemulatorer** [comment]
Xposed Framework v90-beta3 package by topjohnwu
Root Manager Magisk 20.4 by topjohnwu
[Xposed & Magisk Logs.zip](https://github.com/BlueCat300/XposedAppSettings/files/5192208/Xposed.Magisk.Logs.zip)

**Comment by BlueCat300** [comment]
> Android 6.0.1

This module is a fork for Android 8.0+. For lower OS versions use the original module located [here](https://forum.xda-developers.com/showpost.php?p=75681490&postcount=2703)

**Comment by Gamemulatorer** [comment]
> > Android 6.0.1
> 
> This module is a fork for Android 8.0+. For lower OS versions use the original module located [here](https://forum.xda-developers.com/showpost.php?p=75681490&postcount=2703)
> 
> Some developers make the interface (layouts) strictly for portrait orientation. Forced landscape can create clipping of the interface.

already tried the old version but always/force landscape doesn't work 🥺
